"""Reproduce the reviewed RC-002 candidate from its immutable baseline and checkpoints."""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[2]
def read(path): return json.loads((ROOT/path).read_text(encoding='utf-8'))
s=read('cycles/RC-002/baseline.json')
ff=read('inbox/RC-002/fuel_food.json'); lc=read('inbox/RC-002/local_continuity.json'); tr=read('inbox/RC-002/transition_reserves.json'); h=read('inbox/RC-002/coordinator_health.json'); ir=read('inbox/RC-002/independent_review.json')
def get(section, id): return next(x for x in s[section] if x['id']==id)
def cluster(id): return next(x for x in s['SYSTEM_MAP']['clusters'] if x['id']==id)
def edge(id): return next(x for x in s['CASCADE_GRAPH']['edges'] if x['id']==id)
meta=s['meta']; meta.update(schema_version='1.1', cycle_id='RC-002', completed_on='2026-09-21', baseline='Continuation of RC-001 with the same September20 evidence cutoff; newly discovered evidence is distinguished from new events.', status='Bounded research cycle integrated and validated by coordinator from preserved specialist checkpoints', independent_review='Six independent checks of material RC-001 claims completed; closing peer review of RC-002 additions interrupted. Coordinator source checks and acceptance limitations retained.', canonical_repository='https://github.com/Jaradyne/Dis-Unity', coverage_note='Focused deepening of fuel/food, nutrient-specific production, local continuity and healthcare funding; global and social coverage remain incomplete.')
meta['agent_run_history']=[{'cycle_id':'RC-001','runs':meta.pop('agent_runs')}]
meta['agent_runs']=[{'name':n,'status':'Checkpoint preserved; final turn interrupted by shared usage limit','full_report_received':False} for n in ['independent_review','fuel_food','local_continuity','transition_reserves','workflow_builder']]
meta['runtime_note']='Git records and cycle CLI preserve research; agents run during active sessions only. No unattended research, scheduled digest, outreach or private account data.'
meta['review_scope']={'legacy_checks':6,'new_findings_review':'Coordinator acceptance with limitations','unverified_retrievals':['AC Transit budget could not be independently reopened by coordinator; agent checkpoint retained','September EBMUD live storage not extracted','SFPUC gravity remark not admitted without a recoverable specific citation']}
for agent in [ff,lc,tr,h]:
 for item in agent['sources']:
  if item['id']=='FF-S01': continue
  item=dict(item);item['first_seen_cycle']='RC-002';item['last_checked_by']='coordinator' if item['id']!='LC_SRC03' else 'local_continuity (coordinator reopen failed)'
  item['last_verified_at']='2026-09-21' if item['id']!='LC_SRC03' else '2026-09-20'
  if item['id']=='FF-S03':
   item['publication_date']=None
   item['limitations']+=' Publication date not independently established; observation date is explicit. Preserve selected observations because the latest endpoint rolls forward.'
  if item['id']=='FF-S02': item['limitations']+=' Excludes the Northeast Heating Oil Reserve and New York strategic stocks; published changes use unrounded values.'
  s['SOURCE_LEDGER'].append(item)
def sig(id,title,geo,systems,obs,direction,refs,event,freshness,confidence='High for stated primary observation; downstream inference conditional',label='FACT',status='Active observation',implication=''):
 s['ACTIVE_SIGNALS'].append(dict(id=id,title=title,geography=geo,systems=systems,epistemic_label=label,observation=obs,direction=direction,source_ids=refs,confidence=confidence,freshness=freshness,event_id=event,status=status,implication=implication,first_seen_cycle='RC-002',last_reviewed_cycle='RC-002'))
sig('SIG21','Regional distillate reserves diverge',['United States','East Coast','West Coast'],['diesel','trucking'],ff['findings'][0]['observation'],'mixed',['FF-S02'],'us_distillate_stocks_20260911','September11 estimate; same event as SIG02','High for regional estimates; local delivery reserve unknown',implication='National inventory growth cannot stand in for regional or terminal availability. Do not count district stocks twice inside the national total.')
sig('SIG22','Produce-truck availability is constrained on some lanes',['California','United States','Mexico–Texas'],['trucking','food_logistics','agriculture'],ff['findings'][1]['observation'],'mixed',['FF-S03','FF-S04'],'produce_truck_availability_20260915','September15 reported availability; comparison to prior weeks not established',implication='Adds a physical availability indicator to the cost cluster, but no diesel causality, widespread delivery failure or farm output loss established. Overlapping CA/AZ rows are one observation, not independent events.')
sig('SIG23','Harvest and grain movements continue',['United States'],['agriculture','trucking','food_logistics'],ff['findings'][2]['observation'],'improving',['FF-S05'],'grain_transport_20260917','Mixed observation dates explicitly retained',implication='Counters generalized harvest/logistics stoppage. Grain rail/barge activity is not immediately spare refrigerated delivery capacity.')
sig('SIG24','Mosaic reports phosphate output curtailments',['United States','Brazil'],['fertilizer','industrial','labor','agriculture'],tr['findings'][1]['observation'],'worsening',['TRS02'],'mosaic_phosphate_curtailment_20260827','Late discovery: August27 operator disclosure; subsequent restart unverified',implication='Independent producer corroboration upgrades upstream physical-capacity concern. Distributor rationing and missed application remain unproven; furloughs are a labor cost, not automatically healthy shedding.')
sig('SIG25','Nitrogen output and available-capacity denominator diverge',['North America','United States'],['fertilizer','industrial'],tr['findings'][0]['observation'],'mixed',['TRS01'],'cf_nitrogen_h1_2026','Late discovery: H1 observations released August5',implication='Do not count an idled plant inside available reserve or add gross ammonia to its upgraded downstream products. Restart timing is a forecast.')
sig('SIG26','Dated EBMUD storage baseline recovered',['Bay Area','California'],['water'],lc['findings'][0]['observation'],'unclear',['LC_SRC01'],'ebmud_storage_20260408','Historical April8 observation; September reserve remains unknown',status='Historical baseline; not a current reserve credit',implication='Known spring storage improves structural context; it does not answer present water or treatment continuity.')
sig('SIG27','San Anselmo hub construction complete',['San Anselmo','Bay Area'],['grid','municipal'],lc['findings'][1]['observation'],'improving',['LC_SRC02'],'san_anselmo_hub_completion_20260717','Late discovery: July17 completion and undated current project page',implication='Moves a named hub beyond proposal. Public outage hours, staffed access, tested islanding and usable duration remain unverified; no clinical or regional rescue claim.')
sig('SIG28','AC Transit shares regional fiscal exposure',['Bay Area'],['transit','municipal'],lc['findings'][2]['observation'],'mixed',['LC_SRC03'],'ac_transit_fy27_bridge','September-posted FY27 budget; not actual receipts','Medium: primary budget read by specialist; coordinator reopen failed',status='Provisional budget evidence; independently verified BART/Muni pattern remains primary',implication='Bus substitution needs funded accessible vehicles and drivers; another operator is not automatically an unaffected donor.')
for number,item in zip([29,30],h['signals']):
 item=dict(item);item['id']=f'SIG{number}';item['first_seen_cycle']='RC-002';item['last_reviewed_cycle']='RC-002';s['ACTIVE_SIGNALS'].append(item)
old=get('ACTIVE_SIGNALS','SIG03');old['last_reviewed_cycle']='RC-002';old['review_correction']='September11 stocks above100m do not falsify a forecast for the unfinished September month. Only its treatment as an already observed condition is rejected.'
get('SOURCE_LEDGER','SRC04')['revision_note']='RC-002 independent reviewer found a STEO correction to a table that mislabeled gasoline crack-spread figures as distillate. No numerical margin series admitted from that table.'
edge('EDGE01')['thresholds']+=' Separate carrier diesel-cost exposure from produce-truck availability; a contemporaneous shortage rating alone cannot identify fuel as the cause.'
edge('EDGE02')['source_ids']+=['FF-S03','FF-S04','FF-S05'];edge('EDGE02')['activation_status']='Some reported truck availability constraints observed; missed-delivery branch conditional'
edge('EDGE02')['buffers']+=' September grain rail/barge throughput provides sector-specific counterevidence; Mexico–Texas slight reefer surplus is only a candidate after route/commodity/driver constraints.'
edge('EDGE04')['source_ids']+=['TRS02','TRS01'];edge('EDGE04')['activation_status']='Upstream producer curtailment corroborated; farm-level access loss conditional'
edge('EDGE04')['falsify']+=' Verified restarts, timely distributor fulfillment and nutrient-suitable deliveries would weaken the downstream branch.'
edge('EDGE07')['source_ids']+=['LC_SRC01'];edge('EDGE07')['buffers']+=' Historical reservoir storage does not establish current delivery reserve; map gravity, pumping, treatment and local distribution separately before activating this edge.'
edge('EDGE05')['source_ids']+=['LC_SRC03'];edge('EDGE05')['uncertainty']+=' New AC Transit evidence is specialist-read but coordinator retrieval failed; no quantified substitute fleet.'
s['CASCADE_GRAPH']['edges'].append(dict(id='EDGE13', **{'from':'industrial','to':'fertilizer'},initiating_stress='Sulfur availability and affordability constrain phosphate producers',dependent_system='Phosphate production, agricultural input distribution and workers',mechanism='Unavailable or uneconomic feedstock leads to rate reductions or idling. Company cash preservation can transfer costs to workers and customers.',source_ids=['SRC07','TRS02'],buffers='Alternative sourcing, inventories and preserved restart crews; quantities and lead times unverified',thresholds='Operator-disclosed idling observed; downstream escalation requires distributor or farmer fulfillment evidence',substitutes='Nutrient-appropriate imports/recovery/efficiency; potash and nitrogen cannot replace phosphorus function',time_horizon='Weeks to months; application windows matter',uncertainty='Lost volumes, restart dates, distributor stocks and individual farm exposure unknown',confirm='Continuing reduced output plus unmet phosphate orders near application windows',falsify='Restarts, replenished stocks and normal delivered order completion',activation_status='Producer-level capacity withdrawal observed; downstream cascade conditional'))
hc=dict(h['cascades'][0]);hc.update(id='EDGE14',**{'from':'municipal','to':'healthcare'});s['CASCADE_GRAPH']['edges'].append(hc)
for d in ir['decisions']:
 s['CASCADE_GRAPH']['review_decisions'].append(dict(id='RC002-'+d['id'],claim=', '.join(d['target_ids']),decision=d['decision'],reason=d['factual_basis']+' '+d['implication'],source_ids=d['source_ids'],reviewer='independent_review',scope='RC-001 primary-claim check; not final peer approval of RC-002'))
for id,claim,decision,reason,refs in [
 ('CR01','Phosphate strain is only a price signal','Upgraded','Mosaic names physical idles and curtailments. No farm stockout inferred.',['TRS02']),
 ('CR02','A completed hub proves staffed outage capacity','Not admitted','Construction and solar use verified; outage service duration/access/drill unverified.',['LC_SRC02']),
 ('CR03','A regional reserve can support any other region','Narrowed','CL04 global donor links removed pending a specific compatible offer, route, home reserve and staffing. Europe power is not directly exportable to California.',['SRC17','SRC15']),
 ('CR04','Capital investment establishes hospital operating reserve','Rejected','Restricted capital, grant award and recurring cash are separate. Installed/licensed scanners do not prove current utilization or liquidity.',['RC2H01','RC2H04','RC2H05']),
 ('CR05','New local budget assertion independently reproduced','Limited admission','AC Transit source was read by specialist; coordinator reopen failed. Preserve provenance and medium confidence; existing BART/Muni evidence anchors cluster.',['LC_SRC03']),
 ('CR06','September social escalation and tariff-driven repair failure','Remain unestablished','Focused cycle produced no qualifying new evidence; do not treat unchanged unknowns as improvement.',['SRC14','SRC18','SRC19'])]:
 s['CASCADE_GRAPH']['review_decisions'].append(dict(id='RC002-'+id,claim=claim,decision=decision,reason=reason,source_ids=refs,reviewer='coordinator'))
# Usable reserve requires separate function, availability and donor tests.
s['RESERVES_AND_LIFEBOATS'] += [
 dict(id='RES11',name='Produce-route substitution candidate',type='Possible substitution',source_ids=['FF-S03','FF-S04'],readiness='Slight surplus reported at Mexico–South Texas origins September15; no transferable fleet committed',limits='Perishability, commodity, destination, cross-border rules, driver time, price and existing orders constrain transfer',donor_guardrail='Preserve existing deliveries and rest; verify real uncommitted compatible equipment before diversion',essential_function='Timely food transport'),
 dict(id='RES12',name='San Anselmo Town Hall microgrid',type='Constructed local lifeboat candidate',source_ids=['LC_SRC02'],readiness='Municipal owner confirms completion and current solar use; outage activation/drill not verified',limits='No verified public outage-hours, accessible headcount, battery duration or staffing; not emergency clinical capacity',donor_guardrail='Town Hall and local essential service floor first; no regional surge promise or presumed East Bay access',essential_function='Potential communications and temperature refuge during outages'),
 dict(id='RES13',name='EBMUD dated reservoir baseline',type='Historical water stock observation',source_ids=['LC_SRC01'],readiness='April8 total storage observed; current reserve not credited',limits='Stored raw water is not treated, deliverable, uncommitted September water',donor_guardrail='No export credit until current domestic/environmental commitments, treatment and route capacity known',essential_function='Source-water context'),
 dict(id='RES14',name='Watsonville hospital grant bridge',type='Time-limited financial allocation',source_ids=['RC2H01'],readiness='2026 award listed; current disbursement and cash balance unverified',limits='Named committed award, not open reserve; one-time funds do not prove sustainable operating margin',donor_guardrail='Do not assume funds can be redirected; preserve existing patient services and staffing',essential_function='Potential support for continuing local healthcare')]
get('RESERVES_AND_LIFEBOATS','RES01')['limits']+=' Table6 excludes two public strategic reserve categories; quantities and access to these have not been verified.'
s['ISLANDS_OF_STABILITY'].append(dict(id='ISL06',name='San Anselmo civic microgrid node',source_ids=['LC_SRC02'],offers='Constructed solar/battery hub and a replicable municipal project pathway; potential local refuge/communications',needs_in_return='Staffing, maintenance, accessible operations, food/water and replenishment support',available_surplus='Unknown; no receiving capacity or transferable electricity promised',donor_guardrail='Protect local critical functions and test common-hazard/access limitations before offering help',limits='A local institutional node, not an autonomous municipality or Bay Area rescue guarantee',self_sufficient=False))
get('ISLANDS_OF_STABILITY','ISL01')['source_ids']+=['TRS01'];get('ISLANDS_OF_STABILITY','ISL01')['limits']+=' Nutrients serve different functions; CF available-capacity utilization excludes an idled complex and is not spare capacity.'
get('ISLANDS_OF_STABILITY','ISL02')['source_ids']+=['FF-S05'];get('ISLANDS_OF_STABILITY','ISL02')['limits']+=' Operating grain rail/barge flows do not imply uncommitted refrigerated transport.'
ht=dict(h['transitions'][0]);ht.update(id='TR07',cluster_id='CL06');s['TRANSITION_OPPORTUNITIES'].append(ht)
s['TRANSITION_OPPORTUNITIES'].append(dict(id='TR08',name='Preserve nutrient production skills through temporary idling',cluster_id='CL03',classification='Potential managed shedding with documented worker harm; healthy transition not established',function_to_preserve='Safe restart capability and agronomically necessary phosphate supply',released_assets='Operator-reported furloughed labor/time; no evidence that plants, equipment or capital are transferable',safe_load_release='Temporary uneconomic output reduction only where essential nutrient access remains protected',growth_candidate='Qualified maintenance, compatible alternative feedstock sourcing and nutrient recovery/efficiency',conversion_requirements='Worker-led agreements, income protection, competent process engineering, market demand and reliable feedstock',time_horizon='Months; permanent conversion longer',risks='Loss of skills can lengthen recovery; unsafe input substitution or uncompensated labor must not be booked as resilience',source_ids=['TRS02'],status='Proposed response to observed curtailment; no partner commitments',success_observation='Documented retention/redeployment and restored or substituted essential output without shifting unmanageable load to workers or farms'))
get('TRANSITION_OPPORTUNITIES','TR02')['source_ids']+=['TRS02'];get('TRANSITION_OPPORTUNITIES','TR02')['risks']+=' Phosphorus cannot be replaced by abundant potash; tests and qualified agronomy determine safe reductions.'
get('TRANSITION_OPPORTUNITIES','TR05')['source_ids']+=['LC_SRC02'];get('TRANSITION_OPPORTUNITIES','TR05')['status']='Named municipal construction example verified; proposed partner conversions and outage functions remain unverified'
get('COMMUNITY_COMMONS','COM01')['source_ids']+=['LC_SRC03'];get('COMMUNITY_COMMONS','COM01')['resources']+=' Treat transit partners as potentially co-stressed; require actual funded accessible slots.'
get('COMMUNITY_COMMONS','COM02')['source_ids']+=['FF-S03','FF-S04'];get('COMMUNITY_COMMONS','COM04')['source_ids']+=['LC_SRC02'];get('COMMUNITY_COMMONS','COM05')['source_ids']+=['TRS02']
s['COMMUNITY_COMMONS'].append(dict(id='COM07',name='Care-access and transport coordination card',cluster_id='CL06',status='Proposed; no clinical advice or outreach',who_can_act='Clinic navigators, patient-serving nonprofits, union/community representatives and qualified transport partners',first_steps=['Use public service updates to distinguish actual local imaging availability from launch announcements.','Map existing accessible referral/transport routes with no personal patient data.','Have participating institutions confirm funded slots and handoff responsibility before a pilot.'],protected_floor='Preserve clinically necessary care, confidentiality, accessibility, existing trips and driver rest',success_measure='Fewer avoidable transfer trips and missed appointments without worsening waits or staff burden',resources='Public service information and confirmed navigation/transport capacity; no assumed free clinical or volunteer labor',source_ids=['RC2H04','RC2H05'],recordkeeping='Aggregate service measures only; no personal patient histories'))
cl=cluster('CL01');cl['status']='Observed cost pressure plus selected produce-truck constraints; causality and downstream food-access failure unproven';cl['signal_ids']+=['SIG21','SIG22','SIG23'];cl['source_ids']+=['FF-S02','FF-S03','FF-S04','FF-S05'];cl['buffers'].append('RES11');cl['independence']+=' EIA regional stocks are components of the same national event. USDA availability is distinct, but duplicated lane rows are not independent evidence.'
cl=cluster('CL02');cl['signal_ids'].append('SIG28');cl['source_ids'].append('LC_SRC03');cl['status']='Correlated fiscal exposure; actual future service loss conditional; AC Transit addition provisionally sourced'
cl=cluster('CL03');cl['status']='Producer-level physical curtailment corroborated; farm-order and yield cascade conditional';cl['signal_ids']+=['SIG24','SIG25'];cl['source_ids']+=['TRS01','TRS02'];cl['transition_ids'].append('TR08');cl['independence']='Nutrien and Mosaic are independent operators; observations have different dates and product definitions. Their shared sulfur exposure is one mechanism, not independent shocks.';cl['adaptation']='Preserve safe restart capability and worker income; improve nutrient-specific procurement and input efficiency without assuming interchangeable nutrients.'
cl=cluster('CL04');cl['signal_ids']+=['SIG26','SIG27'];cl['source_ids']+=['LC_SRC01','LC_SRC02'];cl['buffers']+=['RES12','RES13'];cl['lifeboats'].append('RES12');cl['outside_reserve']=['ISL05','ISL06'];cl['donor_note']='Removed Europe/Caribbean as generic local utility rescue links. Re-add only with a specific compatible asset, route, current commitments and protected donor reserve.'
s['SYSTEM_MAP']['clusters'].append(dict(id='CL06',title='Healthcare operating cash / capital replacement / care travel',status='New conditional cluster grounded in dated grant and replacement milestones; present service failure not established',signal_ids=['SIG29','SIG30'],interaction='Restricted capital can improve equipment while operating liquidity remains constrained. Reliable local diagnostics may reduce transfers only if staffed and available.',independence='State award and operator statements concern the same hospital; not independent evidence of statewide failure.',source_ids=['RC2H01','RC2H04','RC2H05'],buffers=['RES14','RES09'],transition_ids=['TR07'],commons_ids=['COM01','COM07'],outside_reserve=[],lifeboats=['RES09'],outside_reserve_note='No nearby staffed clinical surplus verified; do not name a donor based on proximity alone.'))
for n in s['SYSTEM_MAP']['systems']:
 if n['id']=='trucking': n['source_ids']+=['FF-S03','FF-S04','FF-S05'];n['gauges']['LOAD']='High fuel cost; some produce origins report truck shortages';n['gauges']['RESERVE']='Uneven qualitative route availability; transferable surplus unknown'
 if n['id']=='fertilizer': n['source_ids']+=['TRS01','TRS02'];n['gauges']['LOAD']='Phosphate input strain now linked to actual operator curtailments';n['gauges']['RESERVE']='Product-specific: strong potash output, mixed nitrogen; uncommitted phosphate unknown';n['gauges']['RECOVERY']='Restart requires feedstock, margins and retained qualified crews';n['gauges']['CONFIDENCE']='Higher for named producer curtailment; farm-level consequences unknown'
 if n['id']=='water': n['source_ids'].append('LC_SRC01');n['gauges']['RESERVE']='April storage baseline recovered; current deliverable reserve still unknown'
 if n['id']=='healthcare': n['source_ids']+=['RC2H01','RC2H04','RC2H05'];n['gauges']['RESERVE']='No current staffed/cash surplus established; grant awards and restricted capital differ';n['gauges']['GROWTH']='Local imaging replacement installed/licensed; regular service benefit to verify';n['gauges']['CONFIDENCE']='Dated local fiscal/capital evidence; current operational reserve unknown'
 if n['id']=='grid': n['source_ids'].append('LC_SRC02');n['gauges']['LIFEBOAT']='San Anselmo construction confirmed; outage scope and duration not verified'
for geo in s['SYSTEM_MAP']['geographies']:
 if geo['id']=='Bay Area': geo['source_ids']+=['LC_SRC01','LC_SRC02','LC_SRC03'];geo['coverage_gap']='AC Transit budget checkpoint obtained; current water, live substitute fleet, Oakland general fund and housing displacement remain gaps'
 if geo['id']=='California': geo['source_ids']+=['RC2H01','RC2H05'];geo['local_strengths']+='; targeted hospital funding and equipment replacement show adaptation while recurring operations remain separate'
s['SYSTEM_MAP']['geographies'].append(dict(id='Pajaro Valley / Monterey Bay',parent='California',structural_context='Local clinical access depends on hospital, community clinics and travel routes; outside nine-county Bay Area',recent_policy='Named 2026 distressed-hospital grant award and September imaging licensing milestone',local_strengths='Public healthcare district and voter-supported capital replacement',trade_and_infrastructure_dependencies='Clinical labor, operating reimbursement, equipment servicing and accessible transport',reserves_and_neighbors='No quantified donor clinical surplus; one-time grant not recurring reserve',coverage_gap='Current cash, disbursement, regular imaging service and partner capacity',source_ids=['RC2H01','RC2H04','RC2H05']))
coverage={r['area']:r for r in s['SYSTEM_MAP']['coverage_inventory']}
coverage['Trucking/food logistics']['status']='September regional produce-truck availability and grain flow checked; actual missed deliveries, causality and local cold-chain capacity unverified'
coverage['Agriculture/fertilizer']['status']='Second producer corroborates phosphate curtailment; nitrogen denominator checked; farm orders, labor/irrigation impacts incomplete'
coverage['Municipal/transit']['status']='Independent BART/Muni review; AC Transit agent-read provisional addition; broader municipal and actual substitute capacity unknown'
coverage['Water/healthcare']['status']='Dated spring water storage, hospital award and equipment milestone recovered; September water and clinical/cash reserve unknown'
updates={
 'Q01':('highest','partly answered; outcome open','Track persistence and seasonal baseline of USDA origin-specific availability plus actual essential delivery completion; do not assign diesel causality from coincidence.'),
 'Q02':('high','partly answered; local reserve open','Regional September11 figures admitted; obtain newer observations, excluded public reserve access and deliverable stocks.'),
 'Q03':('high','partly answered; substitute capacity open','Reopen AC Transit budget through operator financials and verify adopted service/funded accessible alternatives across shared funding outcomes.'),
 'Q04':('highest','upstream corroborated; downstream open','Check Mosaic restart/output updates, distributor order fills and agronomically important application windows.'),
 'Q05':('high','construction confirmed; outage service open','Seek public San Anselmo commissioning/drill and activation/access information; keep unverified hours and duration unknown.'),
 'Q09':('high','historical water and local health evidence added; present reserve open','Find dated late-summer/September water reports and public PVHCD operating finance/service updates; distinguish capital, cash and staffed capacity.'),
 'Q12':('closed for scoped legacy checks','completed with scope limits','Six independent primary-claim checks saved. RC-002 final peer review remains separate in Q13; do not represent this as a complete source audit.')}
for id,(priority,status,next_action) in updates.items():
 q=get('QUESTIONS_TO_WATCH',id);q.update(priority=priority,status=status,next_public_action=next_action,last_reviewed_cycle='RC-002')
for id,priority,question,why,next_action,owner,refs,trigger in [
 ('Q13','high','Finish independent peer review of RC-002 additions','Closing peer review was interrupted, although six independent legacy checks completed','Review new producer curtailment, truck availability, hub readiness and healthcare cash/capital claims; challenge every donor link','Skeptic',['TRS02','FF-S03','LC_SRC02','RC2H05'],'Next active cycle with agent capacity'),
 ('Q14','high','Do hospital funding and replacement milestones translate into service continuity?','Installed capital and awarded support may not provide current staffed service','Read dated public finance and service reports; verify grant receipt and routine imaging operations','Health + Local + Skeptic',['RC2H01','RC2H05'],'New public board/service release'),
 ('Q15','medium','Is nitrogen-to-diesel-exhaust-fluid a consequential additional dependency?','Producer proposes DEF expansion, but present transport constraint is unproven','Check public finished-DEF production/distribution data and OEM requirements; keep agricultural urea and engine-qualified DEF distinct','Industry + Energy',['TRS01'],'Evidence of finished-product shortage, allocation or actual capacity commissioning')]:
 s['QUESTIONS_TO_WATCH'].append(dict(id=id,priority=priority,question=question,why_it_matters=why,next_public_action=next_action,owner_role=owner,source_ids=refs,revisit_trigger=trigger,status='open',user_manual_work_required=False))
get('QUESTIONS_TO_WATCH','Q04')['source_ids']+=['TRS02','TRS01'];get('QUESTIONS_TO_WATCH','Q05')['source_ids'].append('LC_SRC02');get('QUESTIONS_TO_WATCH','Q09')['source_ids']+=['LC_SRC01','RC2H01','RC2H05']
for action,detail in [
 ('Restored','Canonical RC-001 matched preserved project bundle byte for byte; no baseline reset.'),
 ('Reviewed','Six independent material-claim checks reproduced primary observations. Forecast/current-observation distinction refined; final peer review interrupted by usage limit.'),
 ('Deepened','Regional fuel and produce-truck availability added with positive grain-flow evidence; phosphate branch upgraded by second producer. New healthcare operating/capital distinction added.'),
 ('Narrowed reserves','Constructed hub separated from tested outage service; historical storage not current reserve; unmatched Europe/Caribbean donor links removed from local utility cluster.'),
 ('Built and exercised','Checkpoint CLI validates source references, binds review to exact candidate, blocks lost updates, records changes and recovers interrupted commits. Seven integrity tests passed on Linux; Windows branch untested.'),
 ('Git deployment','Prepared public Dis-Unity repository deployment under user-selected Unlicense, preserving original license commit and RC-001 to RC-002 history. No schedule or external contacts.')]:
 s['CHANGELOG'].append(dict(cycle='RC-002',date='2026-09-21',action=action,details=detail))
(ROOT/'cycles/RC-002/candidate.json').write_text(json.dumps(s,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print('RC-002 candidate:',len(s['ACTIVE_SIGNALS']),'signals,',len(s['CASCADE_GRAPH']['edges']),'edges,',len(s['SOURCE_LEDGER']),'sources')
